In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
resources = pd.DataFrame([[2, 6], [1, 4]], index=['Labour', 'Lithium'], columns=['Food', 'Electric Car'])

In [4]:
resources

         Food  Electric Car
Labour      2             6
Lithium     1             4

In [5]:
resources['Electric Car']

Labour     6
Lithium    4
Name: Electric Car, dtype: int64

In [6]:
Availability = {'Labour':120, 'Lithium':80}

In [7]:
plan_a = {'Food':40, 'Electric Cars':6}

In [8]:
plan_a_resources = resources*plan_a.values()

In [9]:
plan_a_resources['Total'] = plan_a_resources['Food'] + plan_a_resources['Electric Car']

In [10]:
plan_a_resources

         Food  Electric Car  Total
Labour     80            36    116
Lithium    40            24     64

In [11]:
plan_b = {'Food':18, 'Electric Cars':14}

In [12]:
plan_b_resources = resources*plan_b.values()

In [13]:
plan_b_resources['Total'] = plan_b_resources['Food'] + plan_b_resources['Electric Car']

In [14]:
plan_b_resources

         Food  Electric Car  Total
Labour     36            84    120
Lithium    18            56     74

In [15]:
plan_c = {'Food':30, 'Electric Cars':11}

In [16]:
plan_c_resources = resources*plan_c.values()

In [17]:
plan_c_resources['Total'] = plan_c_resources['Food'] + plan_c_resources['Electric Car']

In [18]:
plan_c_resources

         Food  Electric Car  Total
Labour     60            66    126
Lithium    30            44     74

In [19]:
plans_resources = pd.DataFrame(data=[plan_a_resources['Total'], plan_b_resources['Total'], plan_c_resources['Total']],
                                columns=['Labour', 'Lithium'], index=['Plan A', 'Plan B', 'Plan C'])

In [20]:
plans_resources

        Labour  Lithium
Plan A     116       64
Plan B     120       74
Plan C     126       74

In [21]:
plans_resources['Labour']>120

Plan A    False
Plan B    False
Plan C     True
Name: Labour, dtype: bool

In [22]:
plans_resources['Lithium']>80

Plan A    False
Plan B    False
Plan C    False
Name: Lithium, dtype: bool

In [23]:
(plans_resources['Labour']>120) | (plans_resources['Lithium']>80)

Plan A    False
Plan B    False
Plan C     True
dtype: bool

In [24]:
np.where((plans_resources['Labour']>Availability['Labour']) | (plans_resources['Lithium']>Availability['Lithium']), 'Unfeasable', 'Feasable')

array(['Feasable', 'Feasable', 'Unfeasable'], dtype='<U10')

In [25]:
plans_resources['Feasability'] = np.where((plans_resources['Labour']>120) | (plans_resources['Lithium']>80), 'Unfeasable', 'Feasable')

In [26]:
plans_resources

        Labour  Lithium Feasability
Plan A     116       64    Feasable
Plan B     120       74    Feasable
Plan C     126       74  Unfeasable

In [27]:
plans_resources['Feasability']=='Feasable'

Plan A     True
Plan B     True
Plan C    False
Name: Feasability, dtype: bool

In [28]:
plans_resources[plans_resources['Feasability']=='Feasable']

        Labour  Lithium Feasability
Plan A     116       64    Feasable
Plan B     120       74    Feasable

In [29]:
plans_resources_feasable = plans_resources[plans_resources['Feasability']=='Feasable']

In [30]:
plans_resources_feasable

        Labour  Lithium Feasability
Plan A     116       64    Feasable
Plan B     120       74    Feasable

In [31]:
plan_a

{'Food': 40, 'Electric Cars': 6}

In [32]:
plan_b

{'Food': 18, 'Electric Cars': 14}