In [1]:
import pandas as pd

# Read a .csv from a URL with Pandas

https://football-data.co.uk

In [2]:
# reading a csv file from website
df_premier26 = pd.read_csv('https://football-data.co.uk/mmz4281/2627/E0.csv')

In [3]:
df_premier26.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BFEC<2.5,AHCh,B365CAHH,B365CAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,21/08/2026,20:00,Arsenal,Coventry,3,0,H,2,0,...,2.56,-2.00,2.05,1.75,2.05,1.83,2.02,1.74,2.14,1.86
1,E0,22/08/2026,12:30,Hull,Man United,2,0,H,2,0,...,2.56,1.50,1.88,1.98,1.88,1.98,1.82,1.92,1.92,2.06
2,E0,22/08/2026,15:00,Everton,Crystal Palace,2,0,H,1,0,...,1.92,-0.25,2.05,1.80,2.05,1.84,1.96,1.79,2.08,1.90
3,E0,22/08/2026,15:00,Ipswich,Sunderland,2,1,H,1,1,...,1.76,0.00,2.10,1.78,2.10,1.83,1.99,1.77,2.11,1.89
4,E0,22/08/2026,15:00,Nott'm Forest,Leeds,0,1,A,0,0,...,1.77,-0.25,2.10,1.70,2.10,1.75,2.07,1.70,2.19,1.83

In [4]:
# rename columns
df_premier26.rename(columns={'FTHG': 'home_goals', 'FTAG': 'away_goals'}, inplace=True)

In [5]:
df_premier26.head(3)

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,BFEC<2.5,AHCh,B365CAHH,B365CAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,21/08/2026,20:00,Arsenal,Coventry,3,0,H,2,0,...,2.56,-2.00,2.05,1.75,2.05,1.83,2.02,1.74,2.14,1.86
1,E0,22/08/2026,12:30,Hull,Man United,2,0,H,2,0,...,2.56,1.50,1.88,1.98,1.88,1.98,1.82,1.92,1.92,2.06
2,E0,22/08/2026,15:00,Everton,Crystal Palace,2,0,H,1,0,...,1.92,-0.25,2.05,1.80,2.05,1.84,1.96,1.79,2.08,1.90

# Read .csv from Multiple URLs with Pandas

Link: root + season + league

In [6]:
# link structure
"https://football-data.co.uk/mmz4281/" + "2627" + "/" + "E0" + ".csv"

'https://football-data.co.uk/mmz4281/2627/E0.csv'

In [7]:
# create a root variable
root = "https://football-data.co.uk/mmz4281/"

## Multiple leagues

https://football-data.co.uk/mmz4281/2627/E0.csv
https://football-data.co.uk/mmz4281/2627/E1.csv
https://football-data.co.uk/mmz4281/2627/E2.csv
https://football-data.co.uk/mmz4281/2627/E3.csv
https://football-data.co.uk/mmz4281/2627/EC.csv

In [8]:
# creating list of leagues
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']
frames = []

# looping through leagues, read multiple CSVs and append it into a list
for league in leagues:
    df = pd.read_csv(root + '2627' + '/' + league + '.csv')
    frames.append(df)

In [9]:
# length of frames
len(frames)

5

In [10]:
# show 2nd element
frames[1]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BFEC<2.5,AHCh,B365CAHH,B365CAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E1,14/08/2026,20:00,Wolves,Blackburn,2,2,D,1,1,...,2.06,-1.00,1.80,2.05,1.83,2.05,1.77,1.98,1.88,2.09
1,E1,15/08/2026,12:30,Bolton,Preston,2,1,H,2,0,...,1.88,-0.25,2.05,1.80,2.05,1.88,1.96,1.78,2.12,1.87
2,E1,15/08/2026,15:00,Bristol City,Millwall,0,2,A,0,1,...,1.96,0.00,1.80,2.05,1.83,2.05,1.78,1.97,1.88,2.11
3,E1,15/08/2026,15:00,Charlton,Derby,2,1,H,0,1,...,1.70,0.00,1.88,1.98,1.90,1.98,1.85,1.89,1.94,2.03
4,E1,15/08/2026,15:00,Middlesbrough,Lincoln,2,1,H,0,1,...,2.16,-1.00,1.88,1.98,1.88,1.98,1.80,1.94,1.91,2.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,E1,12/09/2026,15:00,Preston,Lincoln,0,1,A,0,0,...,2.10,0.00,1.80,2.05,1.80,2.05,1.76,2.00,1.86,2.13
77,E1,12/09/2026,15:00,Southampton,Bristol City,4,1,H,1,0,...,2.58,-0.75,1.88,1.98,1.88,1.98,1.84,1.90,1.96,2.00
78,E1,12/09/2026,15:00,Swansea,Burnley,3,1,H,2,0,...,2.00,-0.50,2.05,1.75,2.05,1.75,2.02,1.73,2.14,1.86
79,E1,12/09/2026,15:00,Watford,Stoke,1,2,A,0,1,...,1.91,-0.25,1.98,1.88,1.98,1.88,1.92,1.82,2.05,1.94
80,E1,13/09/2026,12:00,Sheffield United,Wolves,0,1,A,0,0,...,2.06,0.25,1.98,1.88,1.98,1.88,1.93,1.81,2.05,1.93

In [11]:
#show last element
frames[-1]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BFEC<2.5,AHCh,B365CAHH,B365CAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,08/08/2026,15:00,Altrincham,Southend,1,3,A,1,1,...,2.26,0.50,1.90,1.90,1.96,1.90,1.89,1.80,1.98,1.97
1,EC,08/08/2026,15:00,Boreham Wood,Tamworth,3,3,D,1,1,...,2.56,-1.00,1.88,1.93,1.88,1.93,1.83,1.88,1.90,2.03
2,EC,08/08/2026,15:00,Boston Utd,Aldershot,0,1,A,0,0,...,2.16,-0.75,1.83,1.98,1.90,1.98,1.82,1.89,1.91,2.05
3,EC,08/08/2026,15:00,Carlisle,Worthing,2,3,A,1,0,...,2.44,-1.00,1.80,2.00,1.91,2.00,1.80,1.91,1.86,2.10
4,EC,08/08/2026,15:00,Eastleigh,Gateshead,2,1,H,1,0,...,2.34,-0.25,1.95,1.85,1.95,1.85,1.89,1.81,1.94,2.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,EC,12/09/2026,15:00,Solihull,Aldershot,1,2,A,1,0,...,2.52,-0.50,1.95,1.85,2.05,1.85,1.95,1.76,2.06,1.92
80,EC,12/09/2026,15:00,Sutton,Scunthorpe,0,2,A,0,1,...,2.38,-0.25,1.83,1.98,1.85,1.98,1.83,1.88,1.86,2.11
81,EC,12/09/2026,15:00,Woking,Altrincham,5,1,H,3,1,...,2.10,-0.25,1.85,1.95,1.85,1.95,1.82,1.89,1.89,2.07
82,EC,12/09/2026,15:00,Yeovil,Fylde,1,4,A,0,2,...,2.30,0.00,2.08,1.73,2.08,1.77,1.97,1.75,2.05,1.87
83,EC,12/09/2026,17:30,Carlisle,Southend,2,2,D,1,0,...,2.46,-0.25,1.93,1.88,1.93,1.88,1.86,1.84,1.94,2.04

## Multiple Seasons

In [12]:
for season in range(20, 26):
    print(str(season) + str(season+1))

2021
2122
2223
2324
2425
2526

In [13]:
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']
frames = []

for league in leagues:
    for season in range(20, 26):
        df = pd.read_csv(root + str(season) + str(season+1) + '/' + league + '.csv', encoding='unicode_escape')
        df.insert(1, 'season', str(season) + str(season+1))
        frames.append(df)

In [14]:
# total frames (6 seasons x 5 leagues)
len(frames)

30

In [15]:
# show first element
frames[0]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,2021,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,...,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87
1,E0,2021,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,...,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12
2,E0,2021,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,...,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04
3,E0,2021,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,...,1.92,-0.50,2.03,1.87,2.04,1.88,2.09,1.91,2.02,1.86
4,E0,2021,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,...,1.73,0.25,1.92,1.98,1.93,1.99,1.95,2.01,1.91,1.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,2021,23/05/2021,16:00,Liverpool,Crystal Palace,2,0,H,1,...,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
376,E0,2021,23/05/2021,16:00,Man City,Everton,5,0,H,2,...,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
377,E0,2021,23/05/2021,16:00,Sheffield United,Burnley,1,0,H,1,...,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
378,E0,2021,23/05/2021,16:00,West Ham,Southampton,3,0,H,2,...,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
379,E0,2021,23/05/2021,16:00,Wolves,Man United,1,2,A,1,...,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88

In [16]:
# show last element
frames[29]

,ï»¿Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,2526,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,2526,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,2526,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,2526,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,2526,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,EC,2526,25/04/2026,12:30,Scunthorpe,Eastleigh,0,1,A,0,...,1.85,1.95,NaN,NaN,1.85,1.95,1.80,1.88,NaN,NaN
548,EC,2526,25/04/2026,12:30,Southend,Wealdstone,2,1,H,2,...,1.83,1.98,NaN,NaN,1.83,1.98,1.78,1.91,NaN,NaN
549,EC,2526,25/04/2026,12:30,Tamworth,Braintree Town,5,1,H,2,...,1.78,2.03,NaN,NaN,1.83,2.03,1.77,1.93,NaN,NaN
550,EC,2526,25/04/2026,12:30,Woking,Halifax,0,1,A,0,...,2.08,1.73,NaN,NaN,2.08,1.75,1.99,1.72,NaN,NaN
551,EC,2526,25/04/2026,12:30,Yeovil,Solihull,1,4,A,1,...,1.78,2.03,NaN,NaN,1.78,2.03,1.73,1.97,NaN,NaN

# Organise all the data in a dictionary

In [17]:
# create a dictionary with original name of league as key
dict_countries = {'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2', 'German Bundesliga':'D1', 'Italian Serie A':'I1', 'English Premier League':'E0', 'English Championship':'E1', 'English League 1':'E2', 'French Ligue 1':'F1'}

In [18]:
dict_countries['Spanish Segunda Division']

'SP2'

In [20]:
for league in dict_countries:
    print(dict_countries[league])

SP1
SP2
D1
I1
E0
E1
E2
F1

In [21]:
dict_historical_data = {}

for league in dict_countries:
    frames = []
    for season in range(20, 26):
        df = pd.read_csv(root + str(season) + str(season+1) + '/' + dict_countries[league] + '.csv', encoding='unicode_escape')
        df.insert(1, 'season', str(season) + str(season+1))
        frames.append(df)
    df_concat = pd.concat(frames)
    dict_historical_data[league] = df_concat

In [23]:
dict_historical_data.keys()

dict_keys(['Spanish La Liga', 'Spanish Segunda Division', 'German Bundesliga', 'Italian Serie A', 'English Premier League', 'English Championship', 'English League 1', 'French Ligue 1'])

In [25]:
dict_historical_data['English Premier League']

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,E0,2021,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,2021,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,2021,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,2021,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,2021,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,NaN,2526,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,...,6.75,1.4,5.25,7.00,1.40,5.25,6.00,1.40,5.25,6.00
376,NaN,2526,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,...,1.90,3.5,3.80,1.95,3.40,3.60,2.05,3.40,3.60,2.05
377,NaN,2526,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,...,1.96,3.4,3.70,2.05,3.40,3.60,2.05,3.40,3.50,2.05
378,NaN,2526,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,...,4.10,1.9,3.40,4.33,1.85,3.50,4.20,1.85,3.50,4.00
379,NaN,2526,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,...,4.35,1.7,4.10,4.50,1.73,4.20,4.33,1.70,4.00,4.20