In [1]:
import pandas as pd

In [2]:
df_movies = pd.read_csv('IMDb movies.csv', low_memory=False)[['imdb_title_id', 'title', 'year', 'genre', 'country']]
df_ratings = pd.read_csv('IMDb ratings.csv')[['imdb_title_id', 'total_votes', 'mean_vote']]

In [3]:
df_movies

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium"
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [4]:
df_ratings

      imdb_title_id  total_votes  mean_vote
0         tt0000009          154        5.9
1         tt0000574          589        6.3
2         tt0001892          188        6.0
3         tt0002101          446        5.3
4         tt0002130         2237        6.9
...             ...          ...        ...
85850     tt9908390          398        5.5
85851     tt9911196          724        7.9
85852     tt9911774          265        7.8
85853     tt9914286          194        9.4
85854     tt9914942          102        6.8

[85855 rows x 3 columns]

# Concat()

## Concatenate vertically

In [5]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'id': ['E', 'F', 'G', 'F'],
                    'age': [40, 21, 19, 24]})

In [6]:
print(df1)
print(df2)

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
  id  age
0  E   40
1  F   21
2  G   19
3  F   24

In [7]:
df = pd.concat([df1, df2], axis=0, ignore_index=True)

In [8]:
df

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
4  E   40
5  F   21
6  G   19
7  F   24

### Exercise

In [9]:
# extract a 50% sample of the original dataframe (df_movies)
df_sample = df_movies.sample(frac=0.5, random_state=1)

In [10]:
# shape of dataframes that we'll concatenate
print(df_sample.shape)
print(df_ratings.shape)

(42928, 5)
(85855, 3)

In [11]:
# concatenate df_movies and df_sample vertically
df_vertical_concat = pd.concat([df_movies, df_sample], axis=0)

In [12]:
df_vertical_concat.shape

(128783, 5)

In [13]:
df_vertical_concat

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
68910,tt2866708,Strange But True,2019,Thriller,Canada
856,tt0020697,L'angelo azzurro,1930,"Drama, Music",Germany
40896,tt0296591,17 fois Cécile Cassard,2002,Drama,France
78673,tt5785200,Machine,2017,"Action, Mystery, Romance",India
11621,tt0057469,"Sandokan, la tigre di Mompracem",1963,"Action, Adventure","Italy, France, Spain"

## Concatenate horizontally

In [14]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'job': ['Doctor', 'Statistician', 'Accountant', 'Developer']})

In [15]:
print(df1)
print(df2)

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
            job
0        Doctor
1  Statistician
2    Accountant
3     Developer

In [16]:
df = pd.concat([df1, df2], axis=1)

In [17]:
df

  id  age           job
0  A   30        Doctor
1  B   23  Statistician
2  C   25    Accountant
3  D   22     Developer

### Exercise

In [18]:
# shape of dataframes that we'll concatenate
print(df_ratings.shape)
print(df_movies.shape)

(85855, 3)
(85855, 5)

In [19]:
df_movies.set_index('imdb_title_id', inplace=True)
df_ratings.set_index('imdb_title_id', inplace=True)

In [20]:
# concatenate df_movies and df_ratings on 'imdb_title_id' (horizontally)
df_horizontal_concat = pd.concat([df_movies, df_ratings], axis=1)

In [21]:
# shape
df_horizontal_concat.shape

(85855, 6)

In [22]:
df_horizontal_concat

,title,year,genre,country,total_votes,mean_vote
imdb_title_id,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

# merge()

In [23]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'id': ['C', 'D', 'E', 'F'],
                    'job': ['Doctor', 'Statistician', 'Accountant', 'Developer']})

In [24]:
print(df1)
print(df2)

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
  id           job
0  C        Doctor
1  D  Statistician
2  E    Accountant
3  F     Developer

## Inner join

In [25]:
df_inner = df1.merge(df2, on='id', how='inner')

In [26]:
df_inner

  id  age           job
0  C   25        Doctor
1  D   22  Statistician

In [27]:
#shapes
print(df1.shape)
print(df2.shape)
print(df_inner.shape)

(4, 2)
(4, 2)
(2, 3)

### Exercise

In [28]:
df_movies

,title,year,genre,country
imdb_title_id,,,,
tt0000009,Miss Jerry,1894,Romance,USA
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
tt0002101,Cleopatra,1912,"Drama, History",USA
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium"
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [29]:
df_ratings

               total_votes  mean_vote
imdb_title_id
tt0000009              154        5.9
tt0000574              589        6.3
tt0001892              188        6.0
tt0002101              446        5.3
tt0002130             2237        6.9
...                    ...        ...
tt9908390              398        5.5
tt9911196              724        7.9
tt9911774              265        7.8
tt9914286              194        9.4
tt9914942              102        6.8

[85855 rows x 2 columns]

In [30]:
# merge df_movies and df_ratings (inner join)
df_movieratings_inner = df_movies.merge(df_ratings, on='imdb_title_id', how='inner')

In [31]:
# alternate
df_movieratings_inner = pd.merge(df_movies, df_ratings, on='imdb_title_id', how='inner')

In [32]:
df_movieratings_inner

,title,year,genre,country,total_votes,mean_vote
imdb_title_id,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [33]:
print(df_movies.shape)
print(df_ratings.shape)
print(df_movieratings_inner.shape)

(85855, 4)
(85855, 2)
(85855, 6)

## Full join

In [34]:
df1

  id  age
0  A   30
1  B   23
2  C   25
3  D   22

In [35]:
df2

  id           job
0  C        Doctor
1  D  Statistician
2  E    Accountant
3  F     Developer

In [36]:
df_outer = df1.merge(df2, on='id', how='outer')

In [37]:
df_outer

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN    Accountant
5  F   NaN     Developer

In [38]:
print(df1.shape)
print(df2.shape)
print(df_outer.shape)

(4, 2)
(4, 2)
(6, 3)

### Exercise

In [39]:
df_movies

,title,year,genre,country
imdb_title_id,,,,
tt0000009,Miss Jerry,1894,Romance,USA
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
tt0002101,Cleopatra,1912,"Drama, History",USA
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium"
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [40]:
df_ratings

               total_votes  mean_vote
imdb_title_id
tt0000009              154        5.9
tt0000574              589        6.3
tt0001892              188        6.0
tt0002101              446        5.3
tt0002130             2237        6.9
...                    ...        ...
tt9908390              398        5.5
tt9911196              724        7.9
tt9911774              265        7.8
tt9914286              194        9.4
tt9914942              102        6.8

[85855 rows x 2 columns]

In [41]:
# merge d_movies and dt_ratings (outer join)
df_movieratings_outer = pd.merge(df_movies, df_ratings, on='imdb_title_id', how='outer')

In [42]:
df_movieratings_outer

,title,year,genre,country,total_votes,mean_vote
imdb_title_id,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

## Exclusive Outer Join

In [43]:
df1

  id  age
0  A   30
1  B   23
2  C   25
3  D   22

In [44]:
df2

  id           job
0  C        Doctor
1  D  Statistician
2  E    Accountant
3  F     Developer

In [45]:
# indicator=True makes '_merge' column
df1.merge(df2, on='id', how='outer', indicator=True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [46]:
# query
df_exclusive = df1.merge(df2, on='id', how='outer', indicator=True
                        ).query("_merge=='left_only' | _merge=='right_only'")

In [47]:
df_exclusive

  id   age         job      _merge
0  A  30.0         NaN   left_only
1  B  23.0         NaN   left_only
4  E   NaN  Accountant  right_only
5  F   NaN   Developer  right_only

In [48]:
df_exclusive.shape

(4, 4)

### Exercise

In [49]:
df_movies

,title,year,genre,country
imdb_title_id,,,,
tt0000009,Miss Jerry,1894,Romance,USA
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
tt0002101,Cleopatra,1912,"Drama, History",USA
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium"
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [50]:
df_ratings

               total_votes  mean_vote
imdb_title_id
tt0000009              154        5.9
tt0000574              589        6.3
tt0001892              188        6.0
tt0002101              446        5.3
tt0002130             2237        6.9
...                    ...        ...
tt9908390              398        5.5
tt9911196              724        7.9
tt9911774              265        7.8
tt9914286              194        9.4
tt9914942              102        6.8

[85855 rows x 2 columns]

In [56]:
# merge df_movies and df_ratings (exclusive outer join)
df_exclusive_movieratings = df_movies.merge(df_ratings, on='imdb_title_id', how='outer',
                                            indicator=True).query("_merge=='left_only' | _merge=='right_only'")

In [52]:
df_exclusive_movieratings

Empty DataFrame
Columns: [title, year, genre, country, total_votes, mean_vote, _merge]
Index: []

In [53]:
df_exclusive_movieratings.shape

(0, 7)

## Left join

In [54]:
df1

  id  age
0  A   30
1  B   23
2  C   25
3  D   22

In [55]:
df2

  id           job
0  C        Doctor
1  D  Statistician
2  E    Accountant
3  F     Developer

In [57]:
df1.merge(df2, on='id', how='left')

  id  age           job
0  A   30           NaN
1  B   23           NaN
2  C   25        Doctor
3  D   22  Statistician

### Exercise

In [60]:
# extract a 50% sample of the df_movies dataframe
df_movies_sample = df_movies.sample(frac=0.5, random_state=6)

In [70]:
print(df_movies.shape)
print(df_movies_sample.shape)
print(df_ratings.shape)

(85855, 4)
(42928, 4)
(85855, 2)

In [67]:
# merge df_movies_sample and df_ratings (left join)
df_movieratings_left = df_movies_sample.merge(df_ratings, on='imdb_title_id', how='left')

In [68]:
df_movieratings_left

,title,year,genre,country,total_votes,mean_vote
imdb_title_id,,,,,,
tt0027818,Jenny,1936,Drama,France,203,6.5
tt0292996,Bug Off!,2001,"Comedy, Family, Fantasy",USA,174,4.4
tt0035962,The Halfway House,1944,"Drama, Fantasy, Mystery",UK,616,7.1
tt0027952,Meet Nero Wolfe,1936,Mystery,USA,142,6.5
tt0816257,Gukgyeong-ui namjjok,2006,Drama,South Korea,150,6.9
...,...,...,...,...,...,...
tt0280496,Yuen chi mo hei,1999,"Action, Crime, Thriller",Hong Kong,244,4.8
tt2386342,Anjaneya,2003,"Action, Crime, Drama",India,261,4.5
tt1597176,Altered States of Plaine,2012,"Drama, Mystery, Sci-Fi",USA,191,5.8
tt0034145,The Saint in Palm Springs,1941,"Crime, Drama, Mystery",USA,615,6.3
tt0119578,Le stagioni dell'amore,1997,"Comedy, Drama, Romance",USA,3278,6.9

In [69]:
df_movieratings_left.shape

(42928, 6)